config/routes.rb
Rails.application.routes.draw do
  resources :photo_booths
  root 'messages#index'
  resources :messages
  # For details on the DSL available within this file, see https://guides.rubyonrails.org/routing.html
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/message.rb
class Message < ApplicationRecord
  validates :title, length: {maximum: 32} , presence: true
  validates :message, length: {maximum: 256} , presence: true
  validates :name, length: {maximum: 32} , presence: true
end

app/models/photo_booth.rb
class PhotoBooth < ApplicationRecord
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
end

app/controllers/messages_controller.rb
class MessagesController < ApplicationController
  before_action :set_message, only: [:show, :edit, :update, :destroy]

  # GET /messages
  # GET /messages.json
  def index
    @messages = Message.all
  end

  # GET /messages/1
  # GET /messages/1.json
  def show
  end

  # GET /messages/new
  def new
    @message = Message.new
  end

  # GET /messages/1/edit
  def edit
  end

  # POST /messages
  # POST /messages.json
  def create
    @message = Message.new(message_params)

    respond_to do |format|
      if @message.save
        format.html { redirect_to @message, notice: 'Message was successfully created.' }
        format.json { render :show, status: :created, location: @message }
      else
        format.html { render :new }
        format.json { render json: @message.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /messages/1
  # PATCH/PUT /messages/1.json
  def update
    respond_to do |format|
      if @message.update(message_params)
        format.html { redirect_to @message, notice: 'Message was successfully updated.' }
        format.json { render :show, status: :ok, location: @message }
      else
        format.html { render :edit }
        format.json { render json: @message.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /messages/1
  # DELETE /messages/1.json
  def destroy
    @message.destroy
    respond_to do |format|
      format.html { redirect_to messages_url, notice: 'Message was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_message
      @message = Message.find(params[:id])
    end

    # Only allow a list of trusted parameters through.
    def message_params
      params.require(:message).permit(:name, :title, :message)
    end
end

app/controllers/photo_booths_controller.rb
class PhotoBoothsController < ApplicationController
  before_action :set_photo_booth, only: [:show, :edit, :update, :destroy]

  # GET /photo_booths
  # GET /photo_booths.json
  def index
    @photo_booths = PhotoBooth.all
  end

  # GET /photo_booths/1
  # GET /photo_booths/1.json
  def show
  end

  # GET /photo_booths/new
  def new
    @photo_booth = PhotoBooth.new
  end

  # GET /photo_booths/1/edit
  def edit
  end

  # POST /photo_booths
  # POST /photo_booths.json
  def create
    @photo_booth = PhotoBooth.new(photo_booth_params)

    respond_to do |format|
      if @photo_booth.save
        format.html { redirect_to @photo_booth, notice: 'Photo booth was successfully created.' }
        format.json { render :show, status: :created, location: @photo_booth }
      else
        format.html { render :new }
        format.json { render json: @photo_booth.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /photo_booths/1
  # PATCH/PUT /photo_booths/1.json
  def update
    respond_to do |format|
      if @photo_booth.update(photo_booth_params)
        format.html { redirect_to @photo_booth, notice: 'Photo booth was successfully updated.' }
        format.json { render :show, status: :ok, location: @photo_booth }
      else
        format.html { render :edit }
        format.json { render json: @photo_booth.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /photo_booths/1
  # DELETE /photo_booths/1.json
  def destroy
    @photo_booth.destroy
    respond_to do |format|
      format.html { redirect_to photo_booths_url, notice: 'Photo booth was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_photo_booth
      @photo_booth = PhotoBooth.find(params[:id])
    end

    # Only allow a list of trusted parameters through.
    def photo_booth_params
      params.require(:photo_booth).permit(:title, :photo)
    end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/messages_helper.rb
module MessagesHelper
end

app/helpers/photo_booths_helper.rb
module PhotoBoothsHelper
end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>MyBlog</title>
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag 'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_pack_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

  <body>
    <%= yield %>
  </body>
</html>

app/views/messages/_form.html.erb
<%= form_with(model: message, local: true) do |form| %>
  <% if message.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(message.errors.count, "error") %> prohibited this message from being saved:</h2>

      <ul>
        <% message.errors.full_messages.each do |message| %>
          <li><%= message %></li>
        <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= form.label :title %>
    <%= form.text_field :title %>
  </div>

  <div class="field">
    <%= form.label :message %>
    <%= form.text_area :message %>
  </div>

  <div class="field">
    <%= form.label :name %>
    <%= form.text_field :name %>
  </div>

  <div class="actions">
    <%= form.submit %>
  </div>
<% end %>

app/views/messages/edit.html.erb
<h1>Editing Message</h1>

<%= render 'form', message: @message %>

<%= link_to 'Show', @message %> |
<%= link_to 'Back', messages_path %>

app/views/messages/index.html.erb
<p id="notice"><%= notice %></p>

<h1>Messages</h1>

<table>
  <thead>
    <tr>
      <th>Title</th>
      <th>Message</th>
      <th>Name</th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @messages.each do |message| %>
      <tr>
        <td><%= message.title %></td>
        <td><%= message.message %></td>
        <td><%= message.name %> </td>
        <td><%= link_to 'Show', message %></td>
        <td><%= link_to 'Edit', edit_message_path(message) %></td>
        <td><%= link_to 'Destroy', message, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'New Message', new_message_path %>

app/views/messages/new.html.erb
<h1>New Message</h1>

<%= render 'form', message: @message %>

<%= link_to 'Back', messages_path %>

app/views/messages/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>name:</strong>
  <%= @message.name %>
</p>

<p>
  <strong>Title:</strong>
  <%= @message.title %>
</p>

<p>
  <strong>Message:</strong>
  <%= @message.message %>
</p>

<%= link_to 'Edit', edit_message_path(@message) %> |
<%= link_to 'Back', messages_path %>

app/views/photo_booths/_form.html.erb
<%= form_with(model: photo_booth, local: true) do |form| %>
  <% if photo_booth.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(photo_booth.errors.count, "error") %> prohibited this photo_booth from being saved:</h2>

      <ul>
        <% photo_booth.errors.full_messages.each do |message| %>
          <li><%= message %></li>
        <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= form.label :title %>
    <%= form.text_field :title %>
  </div>

  <div class="field">
    <%= form.label :photo %>
    <%= form.text_field :photo %>
  </div>

  <div class="actions">
    <%= form.submit %>
  </div>
<% end %>

app/views/photo_booths/edit.html.erb
<h1>Editing Photo Booth</h1>

<%= render 'form', photo_booth: @photo_booth %>

<%= link_to 'Show', @photo_booth %> |
<%= link_to 'Back', photo_booths_path %>

app/views/photo_booths/index.html.erb
<p id="notice"><%= notice %></p>

<h1>Photo Booths</h1>

<table>
  <thead>
    <tr>
      <th>Title</th>
      <th>Photo</th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @photo_booths.each do |photo_booth| %>
      <tr>
        <td><%= photo_booth.title %></td>
        <td><%= photo_booth.photo %></td>
        <td><%= link_to 'Show', photo_booth %></td>
        <td><%= link_to 'Edit', edit_photo_booth_path(photo_booth) %></td>
        <td><%= link_to 'Destroy', photo_booth, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'New Photo Booth', new_photo_booth_path %>

app/views/photo_booths/new.html.erb
<h1>New Photo Booth</h1>

<%= render 'form', photo_booth: @photo_booth %>

<%= link_to 'Back', photo_booths_path %>

app/views/photo_booths/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>Title:</strong>
  <%= @photo_booth.title %>
</p>

<p>
  <strong>Photo:</strong>
  <%= @photo_booth.photo %>
</p>

<%= link_to 'Edit', edit_photo_booth_path(@photo_booth) %> |
<%= link_to 'Back', photo_booths_path %>